### ISSUE TITLE
Exception when parse malformed url

### ISSUE THREAD

**Issue by alphatownsman** [digitalbazaar/pyld#196]
```
from pyld import jsonld

jsonld.parse_url('https:&#x2F;&#x2F;nodebb.org')
```
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/takahe-venv/lib/python3.12/site-packages/pyld/jsonld.py", line 624, in parse_url
    if ((g[0] == 'https' and g[1].endswith(':443')) or
                             ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by mielvds** [comment]
This method was removed in v3.0.0 and its functionality was replaced by `urllib.parse.urlparse`
