### ISSUE TITLE
issue with jsonld.normalize().

### ISSUE THREAD

**Issue by amarts** [digitalbazaar/pyld#99]
I was trying to run sign/verify on the same jsonld samples from https://github.com/digitalbazaar/vc-demo/blob/master/credentials/alumni.jsonld in python.

While trying to run jsonld.normalize() I am getting errors. 

```
Traceback (most recent call last):
  File "/home/amar/work/test/certapp-test/jsonld.py", line 1134, in to_rdf
    expanded = self.expand(input_, options)
  File "/home/amar/work/test/certapp-test/jsonld.py", line 835, in expand
    expanded = self._expand(active_ctx, None, document, options, False)
  File "/home/amar/work/test/certapp-test/jsonld.py", line 2090, in _expand
    active_ctx, element['@context'], options)
  File "/home/amar/work/test/certapp-test/jsonld.py", line 2833, in _process_context
    self._create_term_definition(rval, ctx, k, defined)
  File "/home/amar/work/test/certapp-test/jsonld.py", line 4345, in _create_term_definition
    {'context': local_ctx}, code='invalid term definition')
jsonld.JsonLdError: ('Invalid JSON-LD syntax; @context property values must be strings or objects.',)
Type: jsonld.SyntaxError
Code: invalid term definition
```

**Comment by davidlehn** [comment]
Those examples are not likely to work at the moment since PyLD doesn't yet support the latest 1.1 spec.  Full 1.1 support is a work in progress.

**Comment by amarts** [comment]
Thanks for confirming.

**Comment by davidlehn** [comment]
PyLD 2.0.0 has been released. It should be able to handle those examples.

**Comment by mielvds** [comment]
This was probably fixed in 3.X; verified with CLI in the current master branch with `pyld expand https://raw.githubusercontent.com/digitalbazaar/vc-demo/refs/heads/master/credentials/alumni.jsonld`
